project:
  type: website

website:
  title: "Clojure Civitas"
  favicon: "favicon.ico"
  site-url: "https://clojurecivitas.github.io"
  image: "images/civitas-icon.svg"
  open-graph: true
  navbar:
    logo: "images/civitas-icon.svg"
    logo-alt: "Clojure Civitas Logo"
    right:
      - about.qmd
      - posts.qmd
      - ideas.qmd
      - libs.qmd
      - filter.qmd
      - icon: github
        href: "https://github.com/clojurecivitas/clojurecivitas"

format:
  html:
    theme:
      light: [ flatly ]
      dark: [ darkly ]
    respect-user-color-scheme: true
