project:
  type: website

website:
  title: "Clojure Civitas"
  favicon: "favicon.ico"
  navbar:
    logo: "images/civitas-icon.svg"
    logo-alt: "Clojure Civitas Logo"
    right:
      - posts.qmd
      - ideas.qmd
      - libs.qmd
      - about.qmd
      - icon: github
        href: "https://github.com/timothypratley/clojurecivitas"

format:
  html:
    theme:
      light: [ flatly ]
      dark: [ darkly ]
    respect-user-color-scheme: true
