project:
  type: website

website:
  title: "Clojure Civitas"
  favicon: "favicon.ico"
  site-url: "https://clojurecivitas.github.io"
  image: "images/civitas-icon.svg"
  open-graph: true
  navbar:
    logo: "images/civitas-icon.svg"
    logo-alt: "Clojure Civitas Logo"
    right:
      - about.qmd
      - posts.qmd
      - ideas.qmd
      - libs.qmd
      - filter.qmd
      - icon: github
        href: "https://github.com/ClojureCivitas/clojurecivitas.github.io"

format:
  html:
    theme:
      light: [ flatly, styles.scss, styles-light.scss ]
      dark: [ darkly, styles.scss, styles-dark.scss ]
    respect-user-color-scheme: true

brand:
  light: brand-light.yml
  dark: brand-dark.yml
